plugins {
    id 'com.gradleup.shadow' version '9.3.0'
    id 'java'
    id 'application'
    id 'com.github.ben-manes.versions' version '0.53.0'
}

project.setVersion("0.3.0")

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {   // repositories for Jar's you access in your code
    mavenCentral()
    maven{
        // replace with https://maven.lavalink.dev/snapshots if you want to use a snapshot version.
        url = "https://maven.lavalink.dev/releases"
//        url = "https://maven.lavalink.dev/snapshots"
    }
    maven {
        url 'https://m2.dv8tion.net/releases'
    }
    maven {
        url 'https://jitpack.io'
    }
}

application {
    mainClass = 'com.bob.jr.BobJr'
}


tasks.register('dockerBuild', Exec) {
    dependsOn(shadowJar)
    commandLine 'docker', 'build',
            '--build-arg', "PROJECT_VERSION=${project.version}",
            '-t', "us-central1-docker.pkg.dev/vocal-pathway-313217/private-docker-repo/bob-jr-lava:${project.version}",
            '-t', 'us-central1-docker.pkg.dev/vocal-pathway-313217/private-docker-repo/bob-jr-lava:latest',
            '.'
}

tasks.register('dockerPublish', Exec) {
    dependsOn('dockerBuild')
    commandLine 'docker', 'image', 'push',
            "us-central1-docker.pkg.dev/vocal-pathway-313217/private-docker-repo/bob-jr-lava:${project.version}"
}

tasks.register('dockerPublishLatest', Exec) {
    dependsOn('dockerBuild')
    commandLine 'docker', 'image', 'push',
            'us-central1-docker.pkg.dev/vocal-pathway-313217/private-docker-repo/bob-jr-lava:latest'
}


dependencies {
    implementation platform('com.google.cloud:libraries-bom:20.9.0')
    implementation group: 'com.google.guava', name: 'guava', version: '31.0.1-jre'
    implementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.5.6'
    implementation group: 'org.slf4j', name: 'log4j-over-slf4j', version: '1.7.36'
    implementation group: 'net.logstash.logback', name: 'logstash-logback-encoder', version: '6.6'
    implementation group: 'com.discord4j', name: 'discord4j-core', version: '3.3.0'
    implementation group: 'dev.arbjerg', name: 'lavaplayer', version: '2.2.4'
    implementation group: 'dev.lavalink.youtube', name: 'common', version: '1.16.0'
    implementation group: 'dev.arbjerg', name: 'lavaplayer-natives', version: '2.2.4'
    implementation group: 'com.google.cloud', name: 'google-cloud-texttospeech', version: '1.4.1'
    implementation 'com.google.cloud:google-cloud-logging-logback:0.131.9-alpha'

    implementation 'com.google.cloud:google-cloud-secretmanager'

// Add your dependencies here.
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

shadowJar {
    mergeServiceFiles()

    // add sound files via the Dockerfile process
    exclude "/soundFiles/*"
}

test {
    useJUnitPlatform()
}